name: tests

on:
  pull_request:
    branches:
      - "**"
    types: [opened, synchronize, reopened]
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  tests-ut:
    name: tests-ut
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - run: RUST_BACKTRACE=1 cargo test --lib
  
  tests-func:
    name: tests-func
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - run: RUST_BACKTRACE=1 cargo test --tests -- --nocapture --test-threads=1
