name: tests

on:
  pull_request:
    branches:
      - "**"
    types: [opened, synchronize, reopened]
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - run: cargo test -- --test-threads=1